package org.example.entity;

import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

@Entity
public class User {
    @Id
    @GeneratedValue
    private int id;
    private String email;
    private String username;
    private String password;
    @Enumerated(EnumType.STRING)
    private USER_ROLE userRole;
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL)
    private ShoppingCart shoppingCart;
    @OneToMany(mappedBy = "purchasereceipt",  cascade = CascadeType.ALL)
    private List<PurchaseReceipt> purchaseReceipts;

    /**
     * Default Constructor
     */
    public User() {
        // Id AutoGenerated
        this.email = "N/A";
        this.username = "N/A";
        this.password = "N/A";
        this.userRole = USER_ROLE.CUSTOMER;
        this.shoppingCart = new ShoppingCart(this);
        this.purchaseReceipts = new ArrayList<PurchaseReceipt>();
    }

    /**
     * Constructor for initializing a User entity
     * @param email String of a user's email
     * @param username String of a user's username
     * @param password String of a user's password
     * @param userRole USER_ROLE of a user's role (customer or admin)
     */
    public User(String email, String username, String password, USER_ROLE userRole) {
        this.email = email;
        this.username = username;
        this.password = password;
        this.userRole = userRole;
        this.shoppingCart = new ShoppingCart(this);
        this.purchaseReceipts = new ArrayList<PurchaseReceipt>();
    }

    /**
     * add Purchase Receipt to User Account
     * @param purchaseReceipt PurchaseReceipt to be added
     * @return True if added, False Otherwise
     */
    public boolean addPurchaseReceipt(PurchaseReceipt purchaseReceipt) {
        return this.purchaseReceipts.add(purchaseReceipt);
    }
    /**
     * remove Purchase Receipt to User Account
     * @param purchaseReceipt PurchaseReceipt to be added
     * @return True if removed, False otherwise
     */
    public boolean removePurchaseReceipt(PurchaseReceipt purchaseReceipt) {
        return this.purchaseReceipts.remove(purchaseReceipt);
    }

    /* Getters and setters */
    public int getId() {
        return this.id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public USER_ROLE getUserRole() {
        return this.userRole;
    }
    public void setUserRole(USER_ROLE userRole) {
        this.userRole = userRole;
    }
    public ShoppingCart getShoppingCart() {
        return this.shoppingCart;
    }
    public void setShoppingCart(ShoppingCart shoppingCart) {
        this.shoppingCart = shoppingCart;
    }
    public List<PurchaseReceipt> getPurchaseReceipts() {
        return this.purchaseReceipts;
    }
    public void setPurchaseReceipts(List<PurchaseReceipt> purchaseReceipts) {
        this.purchaseReceipts = purchaseReceipts;
    }

    /**
     * Consider equal if id is the same
     * @param o   the reference object with which to compare.
     * @return True if equal, False otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        User u = (User) o;
        return (this.id == u.id);
    }
}
